### ISSUE TITLE
The riscv-basics.com website has been taken down. 

### ISSUE THREAD

**Issue by dragetd** [arm-facts/arm-basics.com#13]
The original website has been taken down. As much as I love the satire which this repository tries to use to poke at ARM, they have pulled back now.

Which kind of 'finishes' the joke of this site. IMHO leaving it online will turn the narrative into something 'we are honestly trying to badmouth ARM' which is - to my understanding - not the core idea what this was about.

So I tip my hat to this move which was well played and suggest that this website is also taken down soon. So we can get back to cooperative improvement of the RISCV future.

**Comment by xfguo** [comment]
Absolutely you are right, my plan is running a down counter on website and the it will be shutdown or change contents in one month.

**Comment by arm-facts** [comment]
Absolutely you are right, the website will be closed in one week.
Thanks!

**Comment by arm-facts** [comment]
@dragetd 
Fixed in 797055f6b05ea39d58b9fe2eba759ce38691b70c .
