### ISSUE TITLE
This entire web site is detrimental to the ARM business and reputation

### ISSUE THREAD

**Issue by ghost** [arm-facts/arm-basics.com#4]
This is no better than the Microsoft "Get the Facts" campaign of the late 00's [1]. This is a quite frankly disgusting business tactic and I will be forwarding this to Simon Segars at ARM explaining my dismay.

[1] https://web.archive.org/web/20070622152618/http://www.microsoft.com/windowsserver/facts/default.mspx

**Comment by xTibor** [comment]
May I ask a small favor of you? Could you also forward riscv-basics.com to Mr Segars? That is also highly detrimental to ARM's reputation.

**Comment by Gymnasiast** [comment]
@m0xte You're completely right. Problem is that ARM _started_ this farce by launching `riscv-basics.com`. This is merely a response.

**Comment by ghost** [comment]
I’ve already contacted him about riscv-basics.com and how damaging that is to ARM’s reputation as well. 

Believe me there are no winners in these games. Take the moral high ground and shitpost about it on Hacker News or something but don’t join the game.

**Comment by sreehax** [comment]
You do realize that this is a personal opinion, not an attack by a major entity such as the RISC-V Foundation.

**Comment by arm-facts** [comment]
Website will be closed in July 15 2018 23:59:59, London time.
