### ISSUE TITLE
Contributing guidelines?

### ISSUE THREAD

**Issue by NatoBoram** [arm-facts/arm-basics.com#6]
How about having some contributing guidelines to help guide PRs in the right direction?

* Should we allow to edit other people's point?
* Is there a predefined architecture for the document? Do we need one? I was thinking about a section for describing the document, one for the direct counter-points to ARM and one for custom community-brought points in favour of RISC-V.

I'll comment what comes to mind as the day goes on.

**Comment by arm-facts** [comment]
@NatoBoram Thanks for you contributions.

- I don't want to predefine anything at this time.
- ARM is a great company, we only need to list the facts and be objective and fair.
- We really need more references and cites for each of the points, that should be the most important guide.
